"""Add full fleet models with tracking and maintenance

Revision ID: 221fe7a76512
Revises: 
Create Date: 2025-08-08 14:43:04.548365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221fe7a76512'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('odometer', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('registration_exp', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('inspection_exp', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('insurance_exp', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('chargeback', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('manager', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('director', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('building', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_column('building')
        batch_op.drop_column('location')
        batch_op.drop_column('director')
        batch_op.drop_column('manager')
        batch_op.drop_column('department')
        batch_op.drop_column('chargeback')
        batch_op.drop_column('insurance_exp')
        batch_op.drop_column('inspection_exp')
        batch_op.drop_column('registration_exp')
        batch_op.drop_column('hours')
        batch_op.drop_column('odometer')
        batch_op.drop_column('type')
        batch_op.drop_column('body')

    # ### end Alembic commands ###
